spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.202.132:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Admin123!
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hk.blog.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.hk.blog: debug
  file:
    name: log/blog.log
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0



